pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/0079567603568sahal/flask-express-cicd-deployment.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('terraform-aws-flask-express-deployment/flask-backend') {
                    sh '''
                    echo "Installing Flask dependencies..."
                    python3 -m pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Flask Server') {
            steps {
                dir('terraform-aws-flask-express-deployment/flask-backend') {
                    sh '''
                    echo "Starting Flask backend using PM2..."
                    pm2 delete flask-backend || true
                    pm2 start app.py --name flask-backend --interpreter python3
                    pm2 save
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '✅ Flask backend deployed successfully!'
        }
        failure {
            echo '❌ Deployment failed. Check Jenkins console for errors.'
        }
    }
}
