pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/0079567603568sahal/terraform-aws-flask-express-deployment.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                cd flask-backend
                sudo apt update -y
                sudo apt install -y python3-venv python3-pip
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Flask Server') {
            steps {
                sh '''
                cd flask-backend
                . venv/bin/activate
                nohup python3 app.py &
                '''
            }
        }
    }
}
